export const ADD_APPOINTMENT_DETAIL_REQUEST = 'ADD_APPOINTMENT_DETAIL_REQUEST'
export const ADD_APPOINTMENT_DETAIL_DATE = 'ADD_APPOINTMENT_DETAIL_DATE'
export const ADD_APPOINTMENT_DETAIL_TIMESLOT = 'ADD_APPOINTMENT_DETAIL_TIMESLOT'
export const ADD_APPOINTMENT_DETAIL_BARBER = 'ADD_APPOINTMENT_DETAIL_BARBER'
export const ADD_APPOINTMENT_DETAIL_SUCCESS = 'ADD_APPOINTMENT_DETAIL_SUCCESS'
export const ADD_APPOINTMENT_DETAIL_FAIL = 'ADD_APPOINTMENT_DETAIL_FAIL'

export const CREATE_APPOINTMENT_REQUEST = 'CREATE_APPOINTMENT_REQUEST'
export const CREATE_APPOINTMENT_SUCCESS = 'CREATE_APPOINTMENT_SUCCESS'
export const CREATE_APPOINTMENT_FAIL = 'CREATE_APPOINTMENT_FAIL'

export const GET_APPOINTMENT_DETAILS_REQUEST = 'GET_APPOINTMENT_DETAILS_REQUEST'
export const GET_APPOINTMENT_DETAILS_SUCCESS = 'GET_APPOINTMENT_DETAILS_SUCCESS'
export const GET_APPOINTMENT_DETAILS_FAIL = 'GET_APPOINTMENT_DETAILS_FAIL'